global:
  scrape_interval: 20s # Set the scrape interval to every 15 seconds. Default is every 1 minute.  
scrape_configs:
  - job_name: 'gateway' 
    static_configs:
    - targets: ['gateway:3001', 'service-discovery:3000', 'user-service-1:8080', 'user-service-2:8080', 'user-service-3:8080', 'scraper-service-1:8000', 'scraper-service-2:8000', 'scraper-service-3:8000', 'etl-service:8000']